# Generated by Django 5.2.10 on 2026-07-13 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_recruiterprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='recruiter_profiles/'),
        ),
    ]
