# Generated by Django 5.2.10 on 2026-07-02 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
