# Generated by Django 5.2.10 on 2026-07-06 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_company_alter_skill_skill_name_experience_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_media',
            new_name='project_media1',
        ),
        migrations.AddField(
            model_name='project',
            name='project_media2',
            field=models.FileField(blank=True, null=True, upload_to='project_media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_media3',
            field=models.FileField(blank=True, null=True, upload_to='project_media/'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_media4',
            field=models.FileField(blank=True, null=True, upload_to='project_media/'),
        ),
    ]
