# Generated by Django 5.2.10 on 2026-07-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0007_savedjob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('office_address', models.TextField(blank=True)),
                ('interviewer_name', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.application')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_letter', models.FileField(upload_to='offer_letters/')),
                ('other_info', models.TextField(blank=True)),
                ('hr_contact', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(null=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobapp.application')),
            ],
        ),
    ]
