# Generated by Django 5.2.10 on 2026-07-18 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_interview_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='accepted',
        ),
    ]
